### ISSUE TITLE
Cannot create devpod container from another container

### ISSUE THREAD

**Issue by Iyappanj** [loft-sh/devpod-provider-kubernetes#47] opened 2024-07-15 07:55 UTC
I am trying to run devpod up .... command from a container which has access to my Kubernetes cluster and end up with the below error.

07:37:30 info devcontainer up: build image: get image build info: create authentication keychain: authenticate: serviceaccounts "default" is forbidden: User "system:serviceaccount:default:default" cannot get resource "serviceaccounts" in API group "" in the namespace "default"

but from the container I can access all resources of the Kubernetes cluster. Only with the Devpod I have this issue. Any hint ?

@pascalbreuninger

**Comment by pascalbreuninger** [comment] 2024-07-16 07:33
@Iyappanj I'm going to close this ticket as a duplicate of https://github.com/loft-sh/devpod/issues/1172.

Please only open one ticket at a time, we'll get to it when time allows ;)

**Closed by pascalbreuninger** 2024-07-16 07:33 UTC
